spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mysql
    username: root
    password: pivotal!
  main:
    allow-bean-definition-overriding: true    
  batch:
    initialize-schema: always
    job:
       names: conditionalStepLogicJob